# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Playground
email: s.mueller@it.kls-glt.de
description: > # this means to ignore newlines until "baseurl:"
  Playground Projekt zum testen der Github Projekt Seiten Funktion.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gaswarnanlagen.com" # the base hostname & protocol for your site
github_username:  zzeroo

# Build settings
markdown: kramdown
